name: esko_dashboard
description: A Flutter application for Esko tracking system dashboard.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter